### PR TITLE
Some fixes for Linux

### PR DESCRIPTION
**Pull request by nic96**
I made some changes so that everything works on Linux as well as some other minor changes.

### CODE REVIEW

**Comment by Ybalrid** [comment]
Just glancing over theses changes, most of them seems to concern some code cleaning, not specifically Linux compat' fix.

And the other concern the .pro file, so that's regarding the build system, not really the code itself. 

If I may put my 2 cents on this, maybe try to run cmake on a build directory, it's pretty easy and if nothing broken since the last time I tried, it should "just works" under linux (getting you a makefile that will moc, jom and compile all the Qt weird stuff), it may be wiser than relying on a .pro file that itself contains some absolute path to some Ogre source directory.

Again, just my two cents on the matter ^^" 

Anyway, your commit b53cd36f4490326e6c3979862e1f5428f830b4c6 should be necessary, 'cause GCC will not build if this is not fixed 👍 

And what bug 2078b45169b8e58ac380628e997c213d0c795949 does correct? Making this method take a `QString*` is a bit weird, specifically since "==" then will compare pointer values (= memory address) and not the actual text inside the QString. I did not ran the code, but it *smells* like adding a bug doing so. 

If you want to pass a string to a method just to test it's value, maybe consider passing is as a const reference (a `const QString&`) instead of a pointer (a QString*), it's simpler and safer and it would be as efficient to do (if not faster since the compiler may avoid to copy the address into a newly created stack variable)

**Comment by nic96** [comment]
About those paths I agree with you and I might work on it yet. Maybe next weekend.

I was also thinking of the QString being passed by pointer not being the optimal way, but for some reason it worked so I didn't give it much thought.

**Comment by Ybalrid** [comment]
Maybe you can cherry pick the commits that fixes GCC'S complaining (over qualification of symbols) in another branch and submit that as a clean pull request. I think it would be easiest to manage thingd that way for @spookyboo

**Comment by nic96** [comment]
This pull request contains too much unnecessary changes so I'm closing it.

**Comment by nic96** [comment]
> And what bug [2078b45](https://github.com/spookyboo/HLMSEditor/commit/2078b45169b8e58ac380628e997c213d0c795949) does correct?

It corrects the bug I wrote about in [this forum topic](http://www.ogre3d.org/forums/viewtopic.php?f=11&t=84816&start=125#p536904)

> If I may put my 2 cents on this, maybe try to run cmake on a build directory, it's pretty easy and if nothing broken since the last time I tried, it should "just works" under linux (getting you a makefile that will moc, jom and compile all the Qt weird stuff), it may be wiser than relying on a .pro file that itself contains some absolute path to some Ogre source directory.

CMake works. I'm more familiar with qmake than cmake though, but I'll try using cmake in Qt Creator for a while.

**Comment by Ybalrid** [comment]
@nic96 what you should do is open an issue about the problem you find here on this GitHub repo 😉

**Comment by nic96** [comment]
@Ybalrid I'll do that.

I actually do have one issue with cmake. I get:
`terminate called after throwing an instance of 'Ogre::FileNotFoundException'
  what():  OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource barrel.mesh in resource group General or any other group. in ResourceGroupManager::openResource at /home/user/workspace/ogre/OgreMain/src/OgreResourceGroupManager.cpp (line 758)
The program has unexpectedly finished.`
When trying to run HLMSEditor and this is becuase the resources directory common does not get copied to the subdirectory of the build directory aka the CMAKE_BINARY_DIR.

Edit: I now created a pull request for the issue: #20

**Comment by Ybalrid** [comment]
Strange. I need to look a bit more precisely into it. The CMake config *should* work, or at least it *was* working when I got around to propose a fix for it a few months ago.

One dirty fix I may propose you is to use the "bin" directory as your cmake build directory. Nothing prevent you to run cmake there, just that the plugin.cfg files there will be overwritten, and since they are tracked in git by the author, they will show up in git status... But at least theses paths should be correct.

If you want to add a `file(COPY ...)` line in the CMakeList, do that in the UNIX block around line 115

I will probably get around to look into that when I'll be on my actually Linux laptop, here I just have a crappy VM and the OpenGL drivers are broken or something, so aside from fixing compiling stuff I can't do much ^^"

(off topic : BTW Arch is the best distro \o/)

**Comment by nic96** [comment]
> If you want to add a file(COPY ...) line in the CMakeList, do that in the UNIX block around line 115

I already did that after line 120 in pr #20.
> (off topic : BTW Arch is the best distro \o/)

👍 That's what I've been using for the passed 5 years

**Pull request closed without merging**
